# このプロジェクトでは常に custom target を使う
[build]
target = "x86_64-formal-os.json"

# bootimage で std/core を再ビルドする設定（blog_os と同じ）
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# OS なしターゲット用の runner 設定
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
